- name: Download and install k3s server
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION={{ k3s_version }} \
    K3S_TOKEN={{ k3s_token }} \
    sh -s - server {{ k3s_install_extra_args_server }}
  args:
    creates: /usr/local/bin/k3s