---
- name: Enable cgroup on all nodes
  import_tasks: enable-cgroup.yml
  tags:
    - k3s

- name: Install and Configure the master nodes
  import_tasks: install-master-nodes.yml
  when: "'masters' in group_names"
  tags:
    - k3s

- name: Install and Configure the worker nodes
  import_tasks: install-worker-nodes.yml
  when: "'workers' in group_names"
  tags:
    - k3s

