ansible_user: admin
static_interface: eth0
static_ip: 192.168.50.153
static_prefix: 24
static_gateway: 192.168.50.1
static_dns:
  - 192.168.50.1
  - 192.168.50.144 
  - 192.168.50.145 
  - 8.8.8.8
  - 8.8.4.4