$ANSIBLE_VAULT;1.1;AES256
39383236306238646234333865616330636662353739376362303663373966653864396438376232
3461303136613964383033363234663535353335323337630a363332343536663663373963333064
61613535656262333338323164636333363262316662343736363736383861623566373062333531
3763303632396133330a373566363133663336626566656264393563626433356335636362633665
36386166346135313364663434336438303364383037663532303832633430643636393963396433
66623030363334666266363961356333636333323335346536666232336539373937346638333331
626234333966306236326464346437343936
